<a href="https://colab.research.google.com/github/DharaCS23181/Skincare_Product_Prediction/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv("/content/drive/MyDrive/ML Dataset/skin_recommendation_dataset.csv")

df.head()

,skintype,skin_condition,product_type,product_name,brand,notable_effects,picture_src
0,Oily,"('wrinkles', 'pigmentation', 'acne', 'enlarged...",Face Wash,ACWELL Bubble Free PH Balancing Cleanser,ACWELL,"('acne-free', 'pore-care', 'brightening', 'ant...",https://www.beautyhaul.com/assets/uploads/prod...
1,"Normal, Dry, Combination","('redness', 'skin imbalance')",Face Wash,ACWELL pH Balancing Soothing Cleansing Foam,ACWELL,"('soothing', 'balancing')",https://images.soco.id/8f08ced0-344d-41f4-a15e...
2,"Normal, Dry, Oily, Combination, Sensitive","('redness', 'skin imbalance')",Toner,Acwell Licorice pH Balancing Cleansing Toner,ACWELL,"('soothing', 'balancing')","https://www.soco.id/cdn-cgi/image/w=73,format=..."
3,Oily,"('wrinkles', 'pigmentation', 'acne', 'enlarged...",Toner,ACWELL Aquaseal Soothing Tonic,ACWELL,"('acne-free', 'pore-care', 'brightening', 'ant...",https://www.beautyhaul.com/assets/uploads/prod...
4,"Normal, Dry","('pigmentation', 'redness')",Toner,Licorice pH Balancing Essence Mist,ACWELL,"('brightening', 'soothing')","https://www.sociolla.com/cdn-cgi/image/w=425,f..."

In [4]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   skintype         1224 non-null   object
 1   skin_condition   1224 non-null   object
 2   product_type     1224 non-null   object
 3   product_name     1224 non-null   object
 4   brand            1224 non-null   object
 5   notable_effects  1224 non-null   object
 6   picture_src      1224 non-null   object
dtypes: object(7)
memory usage: 67.1+ KB
None
       skintype                                  skin_condition product_type  \
count      1224                                            1224         1224
unique       15                                             100            5
top        Oily  ('wrinkles', 'pigmentation', 'enlarged pores')        Serum
freq        310                                             151          307

                                product_name      brand  \
count                                   1224       1224
unique                                  1192        211
top     Somethinc RESURRECT Multibiome Serum  SOMETHINC
freq                                       4         80

                                   notable_effects  \
count                                         1224
unique                                         142
top     ('pore-care', 'brightening', 'anti-aging')
freq                                           151

                                              picture_src
count                                                1224
unique                                               1182
top     https://d1t5vruya68pwb.cloudfront.net/uploads/...
freq                                                    4

In [5]:
le = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

df.head()

,skintype,skin_condition,product_type,product_name,brand,notable_effects,picture_src
0,10,92,0,40,2,17,311
1,5,71,0,41,2,119,96
2,7,71,4,99,2,119,963
3,10,92,4,39,2,17,310
4,4,57,4,651,2,39,940

In [6]:
X = df.drop("product_name", axis=1)
y = df["product_name"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

Training samples: (979, 6)
Testing samples: (245, 6)

In [12]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [13]:
y_pred = model.predict(X_test)

print("Predicted products:", y_pred[:10])

Predicted products: [ 655    6  369  638  863  293 1071  192  605  481]

In [14]:
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.0163265306122449

In [18]:
new_user = [[1, 2, 0, 1, 1, 2]]

prediction = model.predict(new_user)

print("Recommended Product:", prediction)

Recommended Product: [353]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(